version: '3.1'
services:
  redis:
    image: redis:5.0.5-alpine
    container_name: redis
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
    volumes:
      - /etc/localtime:/etc/localtime
      - /data/redis:/data
    ports:
      - 6379:6379
    privileged: true
    command:
      - /bin/sh
      - -c 
      - |
        echo 1024 > /proc/sys/net/core/somaxconn
        redis-server --appendonly yes
